#source 'https://xxxx/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.xiaojukeji.com:one-ios/Specs.git'
source 'git@git.xiaojukeji.com:ios/cocoapods-specs.git'
platform:ios, '7.0'

# We don't use Swift internally. Disable this option.
#use_frameworks!

# Use local pod code if available.
def local_pod(name, *args)
  path = File.expand_path name, '../..'

  if File.exist? path
    pod name, :path => path
  else
    pod name, *args
  end
end

# Add global dependencies here.

target 'ALFoundation_Example' do
  # If ALFoundation depends on any private pod, remember to use `local_pod`
  # to refer it explicitly.
  # CocoaPods cannot distinguish public and private pod from podspec right now,
  # it's required to do so in Podfile.
  #
  # Sample:
  #   local_pod "AnInternalPod", :git => "https://github.com/alex520biao/path/to/pod.git", :tag => "stable-tag"

  # Add Example specific dependencies here...

  # 调试工具: ALAssert断言封装
  pod "ALDEBugTool",:git => "https://github.com/alex520biao/ALDEBugTool.git", :branch => 'master'
  
  pod "ALFoundation", :path => "../"
end

target 'ALFoundation_Tests' do
  # Add Tests specific dependencies here...

  pod "ALFoundation", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
